import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import Head from 'next/head';

export default function Home() {
  return (
    <div className="bg-zinc-800 text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="hero" className="snap-center">
        <Hero />
      </section>
    </div>
  );
}
