import Head from "next/head";
import Link from "next/link";

import { House } from "phosphor-react";
import { ToastContainer } from "react-toastify";

import { About } from "@/components/About";
import { Header } from "@/components/Header";
import { Hero } from "@/components/Hero";
import { Experiences } from "@/components/Experiences";
import { Skills } from "@/components/Skills";
import { Projects } from "@/components/Projects";
import { ContactMe } from "@/components/ContactMe";

export default function Home() {
  return (
    <div className="z-0 h-screen snap-y snap-mandatory overflow-y-scroll bg-zinc-800 text-white scrollbar overflow-x-hidden scrollbar-track-gray-400/20 scrollbar-thumb-primary">
      <Head>
        <title>tashiro.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://avatars.githubusercontent.com/u/40151349"
        />
      </Head>

      <Header />

      <section id="hero" className="snap-none md:snap-start">
        <Hero />
      </section>

      <section id="about" className="snap-none md:snap-center">
        <About />
      </section>

      <section id="experiences" className="snap-none md:snap-center">
        <Experiences />
      </section>

      <section id="skills" className="snap-none md:snap-start">
        <Skills />
      </section>

      <section id="projects" className="snap-none md:snap-start">
        <Projects />
      </section>

      <section id="contact" className="z-0 snap-none md:snap-start">
        <ContactMe />
      </section>

      <footer className="sticky bottom-5 w-full">
        <div className="flex items-center justify-center">
          <Link
            href="#hero"
            className="transform rounded-full bg-primary p-2 transition-transform duration-300 hover:scale-125"
          >
            <House size={32} color="black" weight="light" />
          </Link>
        </div>
      </footer>

      <ToastContainer theme="colored" />
    </div>
  );
}
